MERGE `{cam_table_id}` T
USING `{staging_table_id}` S
ON 
    -- Vehicle Match
    UPPER(TRIM(CONCAT(IFNULL(T.Make,''), ' ', IFNULL(T.Model,'')))) = UPPER(TRIM(S.Vehicle))
    AND
    -- Size Match
    UPPER(TRIM(CONCAT(IFNULL(T.Width,''), '/', IFNULL(T.Profile,''), ' R', IFNULL(T.Rim,'')))) = UPPER(TRIM(S.Size))
    
WHEN MATCHED THEN
    UPDATE SET
    SKU1=COALESCE(SAFE_CAST(S.SKU1 AS STRING), T.SKU1), SKU2=COALESCE(SAFE_CAST(S.SKU2 AS STRING), T.SKU2), SKU3=COALESCE(SAFE_CAST(S.SKU3 AS STRING), T.SKU3),
    SKU4=COALESCE(SAFE_CAST(S.SKU4 AS STRING), T.SKU4), SKU5=COALESCE(SAFE_CAST(S.SKU5 AS STRING), T.SKU5), SKU6=COALESCE(SAFE_CAST(S.SKU6 AS STRING), T.SKU6),
    SKU7=COALESCE(SAFE_CAST(S.SKU7 AS STRING), T.SKU7), SKU8=COALESCE(SAFE_CAST(S.SKU8 AS STRING), T.SKU8), SKU9=COALESCE(SAFE_CAST(S.SKU9 AS STRING), T.SKU9),
    SKU10=COALESCE(SAFE_CAST(S.SKU10 AS STRING), T.SKU10), SKU11=COALESCE(SAFE_CAST(S.SKU11 AS STRING), T.SKU11), SKU12=COALESCE(SAFE_CAST(S.SKU12 AS STRING), T.SKU12),
    SKU13=COALESCE(SAFE_CAST(S.SKU13 AS STRING), T.SKU13), SKU14=COALESCE(SAFE_CAST(S.SKU14 AS STRING), T.SKU14), SKU15=COALESCE(SAFE_CAST(S.SKU15 AS STRING), T.SKU15),
    SKU16=COALESCE(SAFE_CAST(S.SKU16 AS STRING), T.SKU16), SKU17=COALESCE(SAFE_CAST(S.SKU17 AS STRING), T.SKU17), SKU18=COALESCE(SAFE_CAST(S.SKU18 AS STRING), T.SKU18),
    SKU19=COALESCE(SAFE_CAST(S.SKU19 AS STRING), T.SKU19), SKU20=COALESCE(SAFE_CAST(S.SKU20 AS STRING), T.SKU20), SKU21=COALESCE(SAFE_CAST(S.SKU21 AS STRING), T.SKU21),
    SKU22=COALESCE(SAFE_CAST(S.SKU22 AS STRING), T.SKU22), SKU23=COALESCE(SAFE_CAST(S.SKU23 AS STRING), T.SKU23), SKU24=COALESCE(SAFE_CAST(S.SKU24 AS STRING), T.SKU24),
    last_modified=S.last_modified
    
WHEN NOT MATCHED THEN
    INSERT (Make, Model, Width, Profile, Rim, 
            SKU1, SKU2, SKU3, SKU4, SKU5, SKU6, SKU7, SKU8, SKU9, SKU10, SKU11, SKU12,
            SKU13, SKU14, SKU15, SKU16, SKU17, SKU18, SKU19, SKU20, SKU21, SKU22, SKU23, SKU24,
            last_modified)
    VALUES (S.Make, S.Model, S.Width, S.Profile, S.Rim,
            S.SKU1, S.SKU2, S.SKU3, S.SKU4, S.SKU5, S.SKU6, S.SKU7, S.SKU8, S.SKU9, S.SKU10, S.SKU11, S.SKU12,
            S.SKU13, S.SKU14, S.SKU15, S.SKU16, S.SKU17, S.SKU18, S.SKU19, S.SKU20, S.SKU21, S.SKU22, S.SKU23, S.SKU24,
            S.last_modified)
